package com.myteam.quote;

rule "init"
    dialect "mvel"
    when 
        Quote()
    then
        Quote quote = new Quote();
end
     

//from row number: 1
//young
rule "Row 1 quoting"
	dialect "mvel"
	when
		f1 : driver( age > 18 , age <= 25 )
		quote: Quote()
	then
		quote.setPrice( quote.getPrice() + 100.0 );
		update( quote );
end

//from row number: 2
//young adult
rule "Row 2 quoting"
	dialect "mvel"
	when
		f1 : driver( age > 26 , age <= 35 )
		quote: Quote()
	then
		quote.setPrice( quote.getPrice() + 200.0 );
		update( quote );
end

//from row number: 3
//adult
rule "Row 3 quoting"
	dialect "mvel"
	when
		f1 : driver( age > 36 , age <= 50 )
		quote: Quote()
	then
		quote.setPrice( quote.getPrice() + 300.0 );
		update( quote );
end

//from row number: 4
//old
rule "Row 4 quoting"
	dialect "mvel"
	when
		f1 : driver( age > 51 )
		quote: Quote()
	then
		quote.setPrice( quote.getPrice() + 450.0 );
		update( quote );
end

//from row number: 5
//few  fines
rule "Row 5 quoting"
	dialect "mvel"
	when
		f1 : driver( fines > 0 , fines <= 2 )
	then
		quote.setPrice( quote.getPrice() + 150.0 );
		update( quote );
end

//from row number: 6
//some fines
rule "Row 6 quoting"
	dialect "mvel"
	when
		f1 : driver( fines > 3 , fines <= 5 )
		quote: Quote()
	then
		quote.setPrice( quote.getPrice() + 250.0 );
		update( quote );
end

//from row number: 7
//lot of fines
rule "Row 7 quoting"
	dialect "mvel"
	when
		f1 : driver( fines > 6 )
		quote: Quote()
	then
		quote.setPrice( quote.getPrice() + 400.0 );
		update( quote );
end

