package com.myteam.quote;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class driver implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public driver() {
    }




}