package com.myteam.quote;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Quote implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Quote() {
    }




}