package com.myteam.quote;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Quote implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Price")
	private Integer price;

	@org.kie.api.definition.type.Label(value = "Driver")
	private com.myteam.quote.driver driver;

	public Quote() {
	}

	public java.lang.Integer getPrice() {
		return this.price;
	}

	public void setPrice(java.lang.Integer price) {
		this.price = price;
	}

	public com.myteam.quote.driver getDriver() {
		return this.driver;
	}

	public void setDriver(com.myteam.quote.driver driver) {
		this.driver = driver;
	}

	public Quote(java.lang.Integer price, com.myteam.quote.driver driver) {
		this.price = price;
		this.driver = driver;
	}

}