package com.redhat.insurancequoting;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Quote implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private Integer price;

	private com.redhat.insurancequoting.Driver driver;

	public Quote() {
	}

	public com.redhat.insurancequoting.Driver getDriver() {
		return this.driver;
	}

	public void setDriver(com.redhat.insurancequoting.Driver driver) {
		this.driver = driver;
	}

	public java.lang.Integer getPrice() {
		return this.price;
	}

	public void setPrice(java.lang.Integer price) {
		this.price = price;
	}

	public Quote(java.lang.Integer price,
			com.redhat.insurancequoting.Driver driver) {
		this.price = price;
		this.driver = driver;
	}

}