package com.redhat.insurancequoting;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Quote implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Double price;

	public Quote() {
	}

	public java.lang.Double getPrice() {
		return this.price;
	}

	public void setPrice(java.lang.Double price) {
		this.price = price;
	}

	public Quote(java.lang.Double price) {
		this.price = price;
	}

}