package com.redhat.insurancequoting;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Vehicle implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Vehicle() {
    }




}